config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users

  root 'user_sessions#index'

  resources :users, only: [:new, :create]

  resources :user_sessions, only: [:create, :destroy]

  get '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/users/new', to: 'users#new', as: :register
  get '/error', to: 'shared#errors', as: :error
  get '/follow/:id', to: 'user_sessions#follow', as: :follow

  get 'posts/new' => 'posts#new'

  get 'posts/(:id)/delete' => 'posts#destroy', as: "delete"

  get 'posts/(:id)/edit' => 'posts#edit', as: "edit"

  get 'posts/(:id)' => 'posts#show', as: "show"

  resources :my_resources do
    get 'page/:page', :action => :index, :on => :collection 
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic
  acts_as_followable
  acts_as_follower

  acts_as_authentic do |c|
      c.login_field = 'email'
  end



  validates_presence_of :name, :username, :email, :bio
  validates :bio, length: { minimum: 20 }
  validates :username, length: { minimum: 5 }

  has_many :posts


end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




  private

  def post_params
    params.require(:post).permit(:blurb)
  end

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  helper_method :current_user_session, :current_user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
    @post = Post.new(post_params)
    @post.update(user_id: current_user.id)
    if @post.save
      flash[:success] = "Your Post Was a Success!"
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @posts = Post.all
    @post = Post.new
end
  def edit
    @post = Post.find(params[:id])
    @post.save
    render :new
  end

def update
   @post = Post.find(params[:id])
   if @post.update(post_params)
     redirect_to @post
   else
     render "new"
   end
 end

def show
    @posts = Post.find(params[:id])
    render "post"
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    Post.all
    redirect_to root_path
    @post.save

  end

end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
def error
end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController


  def new
    @user_session = UserSession.new
  end
  def index
    if current_user_session
      follower_ids = ""
      current_user.all_following.each do |f|
        follower_ids = follower_ids +", "+ f.id.to_s
      end
      @posts = Post.select("posts.*").where("user_id IN (" + current_user.id.to_s + follower_ids+")").order(:created_at.to_s + " DESC").page(params[:page]).per(50)
    else
      @posts = Post.select("posts.*").order(:created_at).page(params[:page]).per(50)
    end
  end
  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
    end
  end
  def follow
    user1 = current_user
    user2 = User.find(params['id'])
    user1.follow(user2)
    redirect_to :back
  end

  def destroy
      current_user_session.destroy
      flash[:success] = "Goodbye!"
      redirect_to root_path
  end



  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index

  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params['id'])
    render "new"
  end

  def show
    @user = User.find(params['id'])
  end



  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user =User.find(params['id'])
    if @user.update(users_params)
      flash[:success] = "Account Updated!"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private

  def users_params
    params.require(:user).permit(:bio, :email, :password, :password_confirmation,:profile_picture,:username,:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamTriadTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/shop-item.css" rel="stylesheet">
</head>
<body>
  <% if flash[:success] %>
  <center><div class="success"><%= flash[:success] %></div></center>
  <% end %>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button><div class="navbar-brand">
              <% if current_user_session %>
              <%= link_to "LOGOUT", sign_out_path %>
              <% else %>
              <%= link_to "LOGIN", sign_in_path %>
              <% end %>
          </div></div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to "Home", root_path %>
                  </li>
                  <li>
                      <%= link_to "All Users", users_path %>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>


      <!-- /.container -->
  </nav>
  <div class="container">

      <div class="col-md-3">
  <div class="row">
      <p class="lead">Blurber</p>
      <div class="list-group">
          <a href="<%= new_post_path %>" class="list-group-item active">New Post</a>
          <a href="#" class="list-group-item">Followers</a>
          <a href="#" class="list-group-item">Following</a>
      </div>
    <div class="login/out">
    <% if !current_user_session %>
        <center><div id="custom-form-index">
          <div class="page-header"><h1>Sign In</h1></div>
        <%  @user_session = UserSession.new %>
        <%= form_for @user_session do |f| %>
          <%#= render 'shared/errors', object: @user_session %>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :remember_me %>
            <%= f.check_box :remember_me %>
          </div>

        <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %> <button type = "button" class = "btn btn-primary btn-lg btn-sign-up" onclick="location.href='<%= register_path %>';">Sign Up!</button>

      <% end %>
      </div>
    <% else %>
      <button type = "button" class = "btn btn-primary btn-lg btn-sign-up" onclick="location.href='<%= sign_out_path %>';">Log Out!</button>
    <% end %>

</div>
</div>
</div>
<div class="col-md-6 body-class">
<%= yield %>
</div>
</body>
</html>

app/views/posts/new.html.erb
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <% if params[:action] == "new" || params[:action] == "create" %>
                <h2 class="post-title">New post</h1>
              <% else %>
                <h2 class="post-title">Edit post</h1>
              <% end %>

              <%= form_for @post do |f| %>
              <div style="padding-bottom: 10px;" class="form_group">
                <%= f.text_area :blurb, size: "60x12" %>
              </div>
                <%#= f.text_area :blurb, size: "60x12" %>
                <% @posts = Post.all %>
                <% @posts.each do |p| %>
                <% p.user_id %>
                <% end %>
                <%# if current_user_session %>
  <h6><form name="myForm" action="<%= new_post_path %>" method="get">
  <input type="submit" value="SAVE">
</form></h6> <% end %>

                <hr>
                <!-- Pager -->

            </div>
        </div>

app/views/posts/post.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <% @post1 = Post.find(params[:id].to_i) %>

          <div class="n">
              <h2 class="post-title"></h2>
                    <p class="post-subtitle" style="font-weight: normal;">
                      <%=raw sanitize(simple_format(@post1.blurb), :tags => %w(br p) ) %>
                    </p>
                </a>

                <p class="post-meta">Posted on <%= @post1.created_at %></p>
                <%= link_to "HOME", root_path  %>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/errors.html.erb
<!--<%# if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <%# object.errors.full_messages.each do |msg| %>
        <li><%#=# msg %></li>
      <%# end %>
    </ul>
  </div>
<%# end %>-->
<center><header style="color: red;">ERROR!</header></center>

app/views/user_sessions/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blurber</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/shop-item.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>




    <!-- Page Content -->
    <div class="container">
      <%= paginate @posts %>

        <div class="row">



            <div id="posts-col" class="col-md-9">


        <h4 class="pull-right"></h4>
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <% @posts.each do |p| %>
            <div class="post-preview">
                <h3 class="post-body" style="font-weight: normal;">
                <%= link_to p.user.username, user_path(id:p.user.id) %>
                </h3>
                <%=raw sanitize(simple_format(p.blurb), :tags => %w(br p em) ) %>
                <p class="post-meta">Posted on <%= p.created_at %></p>
            <% if current_user_session %>
                <%= link_to "DELETE", post_path(id:p.id), :method => :destroy %>
                <%= link_to "EDIT", post_path(id:p.id), :method => :edit %>
            <% end %>
            </div>

        <% end %>


    </div>

    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                  <!--  <p>Copyright &copy; Your Website 2014</p> -->
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/user_sessions/new.html.erb
<center><div id="custom-form">
  <div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
  <%#= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label "Email" %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %>
  </div>

  <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %> <button type = "button" class = "btn btn-primary btn-lg btn-sign-up" onclick="location.href='<%= register_path %>';">Sign Up!</button>

<% end %>

</div></center>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
<% User.all.each do |u| %>
  <li><%= link_to u.username, user_path(id:u.id) %> <% if current_user_session %><%= link_to "edit", edit_user_path(id:u.id) %><% end %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<center><h1>Welcome to Blurb</h1>

<div id="custom-form-signup">
<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :username, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bio, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :bio, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Profile Picture URL", class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.url_field :profile_picture, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <%= f.submit "Save", class: "center-block btn btn-default"%>
  </div>
<% end %>
</div></center>

app/views/users/show.html.erb
<div class="thumbnail col-xs-8">
  <div class="caption-full">
    <h2><%= @user.name %></h2>
    <%= link_to "Follow this User", follow_path(id:@user.id), class:"btn btn-primary" %>
    <h4>Username: <%= @user.username %></h4>

    <h4>Bio: </h4>
    <p><%= @user.bio %></p>
    <h4>Email: <%= mail_to @user.email %></h4>
  </div>
</div>
<div class="col-xs-4">
  <%= image_tag(@user.profile_picture) %>
</div>

</div>
<div class="container center-block">
  <div class="col-xs-6">
    <h1>Followers</h1>
    <ul>
      <% @user.followers.each do |u| %>
        <li><%= link_to User.find(u.id).username, user_path(id:u.id) %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-3">
    <h1>Following</h1>
    <ul>
      <% @user.all_following.each do |u| %>
        <li><%= link_to User.find(u.id).username, user_path(id:u.id) %></li>
      <% end %>
    </ul>
  </div>
</div>